import { Game } from './types';

export const MOCK_GAMES: Game[] = [
  {
    id: '1',
    title: 'Neon City: Uprising',
    price: 59.99,
    discountPrice: 49.99,
    genre: 'RPG',
    platform: 'PC',
    rating: 4.8,
    releaseYear: 2024,
    image: 'https://picsum.photos/800/600?random=1',
    description: 'Survive in a dystopian metropolis where augmentations are the key to power. Open world action RPG with deep customization.',
    isNew: true,
    isTrending: true,
  },
  {
    id: '2',
    title: 'Starship Commander X',
    price: 69.99,
    genre: 'Simulation',
    platform: 'PS5',
    rating: 4.5,
    releaseYear: 2023,
    image: 'https://picsum.photos/800/600?random=2',
    description: 'Command your fleet across the galaxy. Realistic physics and massive multiplayer battles.',
    isTrending: true,
  },
  {
    id: '3',
    title: 'Shadow Ninja Zero',
    price: 39.99,
    genre: 'Action',
    platform: 'Switch',
    rating: 4.7,
    releaseYear: 2024,
    image: 'https://picsum.photos/800/600?random=3',
    description: 'Fast-paced stealth action in a futuristic feudal Japan.',
    isNew: true,
  },
  {
    id: '4',
    title: 'Cyber Rally 2077',
    price: 49.99,
    genre: 'Racing',
    platform: 'Xbox',
    rating: 4.2,
    releaseYear: 2022,
    image: 'https://picsum.photos/800/600?random=4',
    description: 'High octane anti-gravity racing on neon tracks.',
  },
  {
    id: '5',
    title: 'Void Walker',
    price: 29.99,
    genre: 'Adventure',
    platform: 'PC',
    rating: 4.6,
    releaseYear: 2021,
    image: 'https://picsum.photos/800/600?random=5',
    description: 'Explore the emptiness of space and discover ancient alien artifacts.',
  },
  {
    id: '6',
    title: 'Mech Warrior Omega',
    price: 59.99,
    discountPrice: 39.99,
    genre: 'Shooter',
    platform: 'PS5',
    rating: 4.3,
    releaseYear: 2023,
    image: 'https://picsum.photos/800/600?random=6',
    description: 'Customize your mech and dominate the battlefield.',
    isTrending: true,
  },
  {
    id: '7',
    title: 'Pixel Fantasy VII',
    price: 59.99,
    genre: 'RPG',
    platform: 'Switch',
    rating: 4.9,
    releaseYear: 2024,
    image: 'https://picsum.photos/800/600?random=7',
    description: 'A classic turn-based RPG reimagined with stunning 2.5D graphics.',
    isNew: true,
  },
  {
    id: '8',
    title: 'Zombie Outbreak 4',
    price: 45.00,
    genre: 'Horror',
    platform: 'Xbox',
    rating: 4.1,
    releaseYear: 2022,
    image: 'https://picsum.photos/800/600?random=8',
    description: 'Survive the horde with up to 4 friends in co-op mode.',
  }
];

export const MOCK_USER = {
  id: 'u1',
  name: 'Vanshika',
  email: 'vanshika@rohan.com',
  role: 'user' as const
};
